<?php
ob_start();
require('./fpdf/fpdf.php');
include('../registration/session.php');
include('../include/dbconn.php');

if ($_SESSION['level'] != 1) {
    header("Location: ../index.php");
    exit();
}

class PDF extends FPDF {
    function Footer() {
        $this->SetY(-30);
        $this->SetFont('Arial','I',10);
        $this->Cell(0,10,"Generated on: ".date('d M Y, h:i A'),0,1,'R');
        $this->Cell(0,10,"Generated by: {$_SESSION['username']}",0,1,'R');
        $this->SetFont('Arial','I',8);
        $this->Cell(0,10,'Sukahati Cafe | Tel: 017-5030138 | sukahati@example.com',0,1,'C');
        $this->Cell(0,10,'Page '.$this->PageNo().' of {nb}',0,0,'C');
    }
}

$start_date = $_GET['start_date'] ?? date('Y-m-d', strtotime('-7 days'));
$end_date = $_GET['end_date'] ?? date('Y-m-d');
$title = "Order Report from " . date('d M Y', strtotime($start_date)) . " to " . date('d M Y', strtotime($end_date));


// Query for orders
$sql = "
    SELECT o.order_id, o.order_date, u.username AS customer_name, o.total, su.fullName AS staff_name, o.status
    FROM orders o
    JOIN user u ON o.user_id = u.user_id
    LEFT JOIN staff_profile sp ON o.staff_id = sp.staff_id
    LEFT JOIN user su ON sp.user_id = su.user_id
    WHERE DATE(o.order_date) BETWEEN '$start_date' AND '$end_date'
    ORDER BY o.order_date DESC
";
$result = mysqli_query($dbconn, $sql);

// Query for top 3 items
$top_items_result = mysqli_query($dbconn, "
    SELECT p.name, SUM(od.quantity) as total_sold
    FROM orders o
    JOIN order_details od ON o.order_id = od.order_id
    JOIN products p ON od.product_id = p.product_id
    WHERE DATE(o.order_date) BETWEEN '$start_date' AND '$end_date'
    GROUP BY od.product_id
    ORDER BY total_sold DESC
    LIMIT 3
");

// Query for order status summary
$status_summary = [];
$status_query = mysqli_query($dbconn, "
    SELECT o.status, COUNT(*) AS count
    FROM orders o
    WHERE DATE(o.order_date) BETWEEN '$start_date' AND '$end_date'
    GROUP BY o.status
");
while ($row = mysqli_fetch_assoc($status_query)) {
    $status_summary[$row['status']] = $row['count'];
}

$pdf = new PDF();
$pdf->SetMargins(10, 10, 10);
$pdf->AliasNbPages();
$pdf->AddPage();

// Branding
$pdf->Image('../img/sukahaticafe.png',10,6,30);
$pdf->SetFont('Arial','B',16);
$pdf->Cell(0,10,$title,0,1,'C');
$pdf->SetFont('Arial','',12);
//$pdf->Cell(0,10,'From '.date('d M Y', strtotime($start_date)).' to '.date('d M Y', strtotime($end_date)),0,1,'C');
$pdf->Ln(5);

// Top 3 Items
$pdf->SetFont('Arial','B',12);
$pdf->Cell(0,10,'Top 3 Best-Selling Items:',0,1);
$pdf->SetFont('Arial','',12);
$counter = 1;
while ($item = mysqli_fetch_assoc($top_items_result)) {
    $pdf->Cell(0,8,"$counter. {$item['name']} - {$item['total_sold']} sold",0,1);
    $counter++;
}
$pdf->Ln(5);

// Order Status Summary
$pdf->SetFont('Arial','B',12);
$pdf->Cell(0,10,'Order Status Summary:',0,1);
$pdf->SetFont('Arial','',12);
foreach ($status_summary as $status => $count) {
    $pdf->Cell(0,8,ucfirst($status).": $count",0,1);
}
$pdf->Ln(5);

// Summary Before Table
$total_sum = 0;
$order_count = 0;
while ($row = mysqli_fetch_assoc($result)) {
    $total_sum += $row['total'];
    $order_count++;
}

mysqli_data_seek($result, 0);
$pdf->SetFont('Arial','B',12);
$pdf->Cell(0,10,"Total Orders: $order_count",0,1);
$pdf->Cell(0,10,"Total Revenue: RM ".number_format($total_sum, 2),0,1);
$pdf->Ln(5);

// Table headers
$pdf->SetFont('Arial','B',11);
$w_orderId  = 25;
$w_date     = 40;
$w_customer = 50;
$w_total    = 25;
$w_staff    = 50;

$pdf->Cell($w_orderId, 10, 'Order ID', 1, 0, 'C');
$pdf->Cell($w_date, 10, 'Date', 1, 0, 'C');
$pdf->Cell($w_customer, 10, 'Customer', 1, 0, 'C');
$pdf->Cell($w_total, 10, 'Total (RM)', 1, 0, 'C');
$pdf->Cell($w_staff, 10, 'Handled By', 1, 1, 'C');

// Table Rows
$pdf->SetFont('Arial','',11);
while ($row = mysqli_fetch_assoc($result)) {
    $orderId  = $row['order_id'];
    $date     = date('d M Y', strtotime($row['order_date']));
    $customer = $row['customer_name'];
    $total    = number_format($row['total'], 2);
    $staff    = $row['staff_name'] ?: '-';

    $x = $pdf->GetX();
    $y = $pdf->GetY();

    $pdf->SetXY($x, $y);
    $pdf->MultiCell($w_orderId, 10, $orderId, 1, 'C');
    $h1 = $pdf->GetY() - $y;

    $pdf->SetXY($x + $w_orderId, $y);
    $pdf->MultiCell($w_date, 10, $date, 1, 'C');
    $h2 = $pdf->GetY() - $y;

    $pdf->SetXY($x + $w_orderId + $w_date, $y);
    $pdf->MultiCell($w_customer, 10, $customer, 1, 'L');
    $h3 = $pdf->GetY() - $y;

    $pdf->SetXY($x + $w_orderId + $w_date + $w_customer, $y);
    $pdf->MultiCell($w_total, 10, $total, 1, 'C');
    $h4 = $pdf->GetY() - $y;

    $pdf->SetXY($x + $w_orderId + $w_date + $w_customer + $w_total, $y);
    $pdf->MultiCell($w_staff, 10, $staff, 1, 'L');
    $h5 = $pdf->GetY() - $y;

    $rowHeight = max($h1, $h2, $h3, $h4, $h5);

    if ($h1 < $rowHeight) $pdf->Rect($x, $y, $w_orderId, $rowHeight);
    if ($h2 < $rowHeight) $pdf->Rect($x + $w_orderId, $y, $w_date, $rowHeight);
    if ($h3 < $rowHeight) $pdf->Rect($x + $w_orderId + $w_date, $y, $w_customer, $rowHeight);
    if ($h4 < $rowHeight) $pdf->Rect($x + $w_orderId + $w_date + $w_customer, $y, $w_total, $rowHeight);
    if ($h5 < $rowHeight) $pdf->Rect($x + $w_orderId + $w_date + $w_customer + $w_total, $y, $w_staff, $rowHeight);

    $pdf->SetY($y + $rowHeight);
}

ob_end_clean();
$pdf->Output();